In [1]:
import pandas as pd

## OpenCC

In [2]:
# 抽 10% 的 31091 筆 + 未微調 + alpaca
df = pd.read_csv('exp_outputs/asy_mapping_infer_evaluation_results/opencc_inference_result_org_ch_alpaca.csv')
df.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
bl_and_truth_bleu_score,31091.0,0.939139,0.067489,1.054769e-154,9.095931e-01,0.949695,1.000000,1.0
bl_and_truth_gleu_score,31091.0,0.964061,0.037233,5.454545e-01,9.459459e-01,0.969697,1.000000,1.0
model_and_truth_bleu_score,31091.0,0.143937,0.188646,0.000000e+00,3.672183e-155,0.066688,0.234010,1.0
model_and_truth_gleu_score,31091.0,0.253260,0.209433,0.000000e+00,8.724832e-02,0.206009,0.385093,1.0
rev_and_truth_bleu_score,31091.0,0.939570,0.067320,9.530911e-155,9.095931e-01,0.949695,1.000000,1.0
rev_and_truth_gleu_score,31091.0,0.964357,0.037249,4.285714e-01,9.461883e-01,0.970297,1.000000,1.0

In [3]:
# 抽 10% 的 31091 筆 + 微調後 + alpaca
df = pd.read_csv('exp_outputs/asy_mapping_infer_evaluation_results/opencc_inference_result_qlora_1250_ch_alpaca.csv')
df.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
bl_and_truth_bleu_score,31091.0,0.939566,0.068088,9.013779e-155,0.909745,0.949944,1.0,1.0
bl_and_truth_gleu_score,31091.0,0.964333,0.037532,4.545455e-01,0.946706,0.970297,1.0,1.0
model_and_truth_bleu_score,31091.0,0.938943,0.083356,0.000000e+00,0.909593,0.955119,1.0,1.0
model_and_truth_gleu_score,31091.0,0.961799,0.052370,0.000000e+00,0.943820,0.972851,1.0,1.0
rev_and_truth_bleu_score,31091.0,0.958980,0.059610,9.013779e-155,0.934287,0.974418,1.0,1.0
rev_and_truth_gleu_score,31091.0,0.975795,0.032614,4.545455e-01,0.961039,0.984127,1.0,1.0

In [4]:
# 抽 10% 的 31091 筆 + 微調前 + Taiwan LLM
df = pd.read_csv('exp_outputs/asy_mapping_infer_evaluation_results/opencc_inference_result_org_TWLLM.csv')
df.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
bl_and_truth_bleu_score,31091.0,0.939139,0.067489,1.054769e-154,0.909593,0.949695,1.000000,1.0
bl_and_truth_gleu_score,31091.0,0.964061,0.037233,5.454545e-01,0.945946,0.969697,1.000000,1.0
model_and_truth_bleu_score,31091.0,0.226366,0.165595,0.000000e+00,0.103490,0.222460,0.334727,1.0
model_and_truth_gleu_score,31091.0,0.357219,0.165255,0.000000e+00,0.260355,0.373134,0.469136,1.0
rev_and_truth_bleu_score,31091.0,0.941284,0.066106,1.054769e-154,0.911905,0.951643,1.000000,1.0
rev_and_truth_gleu_score,31091.0,0.965365,0.036681,5.714286e-01,0.947368,0.970874,1.000000,1.0

In [5]:
# 抽 10% 的 31091 筆 + 微調後 + Taiwan LLM
df = pd.read_csv('exp_outputs/asy_mapping_infer_evaluation_results/opencc_inference_result_qlora_1250_TLLM.csv')
df.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
bl_and_truth_bleu_score,31091.0,0.939139,0.067489,1.054769e-154,0.909593,0.949695,1.000000,1.0
bl_and_truth_gleu_score,31091.0,0.964061,0.037233,5.454545e-01,0.945946,0.969697,1.000000,1.0
model_and_truth_bleu_score,31091.0,0.474574,0.127337,0.000000e+00,0.403823,0.476818,0.552203,1.0
model_and_truth_gleu_score,31091.0,0.564823,0.094288,0.000000e+00,0.512648,0.566265,0.621622,1.0
rev_and_truth_bleu_score,31091.0,0.945518,0.066065,1.054769e-154,0.916097,0.956676,1.000000,1.0
rev_and_truth_gleu_score,31091.0,0.967819,0.036397,5.454545e-01,0.950413,0.973913,1.000000,1.0

In [6]:
# 抽 10% 的 31091 筆 + 微調前 + TAIDE
df = pd.read_csv('exp_outputs/asy_mapping_infer_evaluation_results/opencc_inference_result_org_TAIDE.csv')
df.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
bl_and_truth_bleu_score,31091.0,0.939139,0.067489,1.054769e-154,9.095931e-01,0.949695,1.000000,1.0
bl_and_truth_gleu_score,31091.0,0.964061,0.037233,5.454545e-01,9.459459e-01,0.969697,1.000000,1.0
model_and_truth_bleu_score,31091.0,0.136933,0.172985,0.000000e+00,5.428796e-155,0.069778,0.224075,1.0
model_and_truth_gleu_score,31091.0,0.266810,0.186427,0.000000e+00,1.267606e-01,0.204611,0.378258,1.0
rev_and_truth_bleu_score,31091.0,0.940597,0.066690,1.603416e-231,9.113481e-01,0.950689,1.000000,1.0
rev_and_truth_gleu_score,31091.0,0.964970,0.036961,3.333333e-01,9.473684e-01,0.970732,1.000000,1.0

In [7]:
# 抽 10% 的 31091 筆 + 微調後 + TAIDE
df = pd.read_csv('exp_outputs/asy_mapping_infer_evaluation_results/opencc_inference_result_qlora_1250_TAIDE.csv')
df.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
bl_and_truth_bleu_score,31091.0,0.939139,0.067489,1.054769e-154,0.909593,0.949695,1.0,1.0
bl_and_truth_gleu_score,31091.0,0.964061,0.037233,5.454545e-01,0.945946,0.969697,1.0,1.0
model_and_truth_bleu_score,31091.0,0.914219,0.098244,0.000000e+00,0.878557,0.931838,1.0,1.0
model_and_truth_gleu_score,31091.0,0.946123,0.066360,0.000000e+00,0.924051,0.958549,1.0,1.0
rev_and_truth_bleu_score,31091.0,0.951817,0.063005,1.054769e-154,0.924359,0.964138,1.0,1.0
rev_and_truth_gleu_score,31091.0,0.971582,0.034520,5.454545e-01,0.954955,0.978417,1.0,1.0

### XMUCC

In [8]:
# XMUCC 原始
df = pd.read_csv('/home/wirl/ytc/要寫的論文研究/code/exp_outputs/raw_inference_results/xmucc_evaluation_results_with_score.csv')
df.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
xmucc_and_truth_bleu_score,31091.0,0.842020,0.105824,1.384293e-231,0.787578,0.852028,0.909745,1.0
xmucc_and_truth_gleu_score,31091.0,0.904487,0.060965,1.818182e-01,0.870270,0.910448,0.945455,1.0

In [9]:
df = pd.read_csv('/home/wirl/ytc/要寫的論文研究/code/exp_outputs/asy_mapping_infer_evaluation_results/XMUCC_inference_result_org_ch_alpaca.csv')
df.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
bl_and_truth_bleu_score,31109.0,0.842047,0.105818,1.384293e-231,7.875785e-01,0.852031,0.909745,1.0
bl_and_truth_gleu_score,31109.0,0.904504,0.060962,1.818182e-01,8.702703e-01,0.910448,0.945455,1.0
model_and_truth_bleu_score,31109.0,0.142612,0.186494,0.000000e+00,3.710927e-155,0.065867,0.232313,1.0
model_and_truth_gleu_score,31109.0,0.252293,0.207571,0.000000e+00,8.860759e-02,0.204819,0.384615,1.0
rev_and_truth_bleu_score,31109.0,0.846644,0.104954,1.384293e-231,7.917687e-01,0.856674,0.914406,1.0
rev_and_truth_gleu_score,31109.0,0.907372,0.060485,1.818182e-01,8.732394e-01,0.913043,0.948571,1.0

In [10]:
df = pd.read_csv('/home/wirl/ytc/要寫的論文研究/code/exp_outputs/asy_mapping_infer_evaluation_results/xmucc_inference_result_qlora_1250_ch_alpaca.csv')
df.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
bl_and_truth_bleu_score,31109.0,0.842047,0.105818,1.384293e-231,0.787578,0.852031,0.909745,1.0
bl_and_truth_gleu_score,31109.0,0.904504,0.060962,1.818182e-01,0.870270,0.910448,0.945455,1.0
model_and_truth_bleu_score,31109.0,0.934200,0.086064,0.000000e+00,0.902772,0.950176,1.000000,1.0
model_and_truth_gleu_score,31109.0,0.958873,0.053662,0.000000e+00,0.940171,0.969697,1.000000,1.0
rev_and_truth_bleu_score,31109.0,0.902454,0.090252,7.657405e-155,0.858707,0.915710,0.963616,1.0
rev_and_truth_gleu_score,31109.0,0.941714,0.050660,3.529412e-01,0.915254,0.949153,0.977778,1.0

In [11]:
df = pd.read_csv('/home/wirl/ytc/要寫的論文研究/code/exp_outputs/asy_mapping_infer_evaluation_results/XMUCC_inference_result_org_TWLLM.csv')
df.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
bl_and_truth_bleu_score,31109.0,0.842047,0.105818,1.384293e-231,0.787578,0.852031,0.909745,1.0
bl_and_truth_gleu_score,31109.0,0.904504,0.060962,1.818182e-01,0.870270,0.910448,0.945455,1.0
model_and_truth_bleu_score,31109.0,0.224341,0.163480,0.000000e+00,0.102009,0.222721,0.330953,1.0
model_and_truth_gleu_score,31109.0,0.355139,0.164691,0.000000e+00,0.257426,0.373134,0.466667,1.0
rev_and_truth_bleu_score,31109.0,0.856810,0.102417,1.384293e-231,0.804051,0.866320,0.923473,1.0
rev_and_truth_gleu_score,31109.0,0.913687,0.058864,1.818182e-01,0.880795,0.919463,0.953488,1.0

In [12]:
df = pd.read_csv('/home/wirl/ytc/要寫的論文研究/code/exp_outputs/asy_mapping_infer_evaluation_results/xmucc_inference_result_qlora_1250_TWLLM.csv')
df.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
bl_and_truth_bleu_score,31109.0,0.842047,0.105818,1.384293e-231,0.787578,0.852031,0.909745,1.0
bl_and_truth_gleu_score,31109.0,0.904504,0.060962,1.818182e-01,0.870270,0.910448,0.945455,1.0
model_and_truth_bleu_score,31109.0,0.474320,0.127538,0.000000e+00,0.403090,0.476191,0.552252,1.0
model_and_truth_gleu_score,31109.0,0.564667,0.094487,0.000000e+00,0.512195,0.565891,0.621622,1.0
rev_and_truth_bleu_score,31109.0,0.879482,0.096327,1.384293e-231,0.832569,0.891471,0.941436,1.0
rev_and_truth_gleu_score,31109.0,0.927515,0.054877,1.818182e-01,0.898305,0.934066,0.964706,1.0

In [17]:
df = pd.read_csv('/home/wirl/ytc/要寫的論文研究/code/exp_outputs/asy_mapping_infer_evaluation_results/xmucc_inference_result_qlora_1250_TAIDE.csv')
df.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
bl_and_truth_bleu_score,31109.0,0.842047,0.105818,1.384293e-231,0.787578,0.852031,0.909745,1.0
bl_and_truth_gleu_score,31109.0,0.904504,0.060962,1.818182e-01,0.870270,0.910448,0.945455,1.0
model_and_truth_bleu_score,31109.0,0.913707,0.098390,0.000000e+00,0.877364,0.931063,1.000000,1.0
model_and_truth_gleu_score,31109.0,0.945773,0.066634,0.000000e+00,0.924051,0.957746,1.000000,1.0
rev_and_truth_bleu_score,31109.0,0.897335,0.092125,1.531972e-231,0.851776,0.909745,0.959491,1.0
rev_and_truth_gleu_score,31109.0,0.938592,0.052250,2.857143e-01,0.910448,0.945946,0.975610,1.0

In [18]:
df = pd.read_csv('/home/wirl/ytc/要寫的論文研究/code/exp_outputs/asy_mapping_infer_evaluation_results/xmucc_inference_result_org_TAIDE.csv')
df.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
bl_and_truth_bleu_score,31109.0,0.842047,0.105818,1.384293e-231,7.875785e-01,0.852031,0.909745,1.0
bl_and_truth_gleu_score,31109.0,0.904504,0.060962,1.818182e-01,8.702703e-01,0.910448,0.945455,1.0
model_and_truth_bleu_score,31109.0,0.136561,0.172528,0.000000e+00,5.484301e-155,0.071023,0.222547,1.0
model_and_truth_gleu_score,31109.0,0.266936,0.185686,0.000000e+00,1.271676e-01,0.205128,0.376812,1.0
rev_and_truth_bleu_score,31109.0,0.846543,0.104279,1.384293e-231,7.918392e-01,0.856458,0.912944,1.0
rev_and_truth_gleu_score,31109.0,0.907411,0.060011,1.818182e-01,8.732394e-01,0.913043,0.947826,1.0

## Google Translate

In [13]:
# 抽 10% 的 31091 筆 + 微調後 + alpaca
df = pd.read_csv('exp_outputs/asy_mapping_infer_evaluation_results/google_inference_result_qlora_1250_ch_alpaca.csv')
df.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
bl_and_truth_bleu_score,31082.0,0.983934,0.036854,1.054769e-154,0.976877,1.000000,1.0,1.0
bl_and_truth_gleu_score,31082.0,0.990443,0.021091,5.714286e-01,0.985915,1.000000,1.0,1.0
model_and_truth_bleu_score,31082.0,0.933897,0.087973,0.000000e+00,0.902663,0.950472,1.0,1.0
model_and_truth_gleu_score,31082.0,0.958605,0.055750,0.000000e+00,0.939759,0.969697,1.0,1.0
rev_and_truth_bleu_score,31082.0,0.975982,0.046911,1.054769e-154,0.960133,1.000000,1.0,1.0
rev_and_truth_gleu_score,31082.0,0.985703,0.025959,5.714286e-01,0.976000,1.000000,1.0,1.0

In [14]:
# 抽 10% 的 31091 筆 + 微調後 + TWLLM
df = pd.read_csv('exp_outputs/asy_mapping_infer_evaluation_results/google_inference_result_qlora_1250_TWLLM.csv')
df.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
bl_and_truth_bleu_score,31082.0,0.983934,0.036854,1.054769e-154,0.976877,1.000000,1.0,1.0
bl_and_truth_gleu_score,31082.0,0.990443,0.021091,5.714286e-01,0.985915,1.000000,1.0,1.0
model_and_truth_bleu_score,31082.0,0.951032,0.078685,1.226322e-233,0.927898,0.969028,1.0,1.0
model_and_truth_gleu_score,31082.0,0.968661,0.050895,2.409639e-02,0.955307,0.980645,1.0,1.0
rev_and_truth_bleu_score,31082.0,0.969627,0.050447,1.054769e-154,0.949695,1.000000,1.0,1.0
rev_and_truth_gleu_score,31082.0,0.981946,0.028216,5.714286e-01,0.969697,1.000000,1.0,1.0

In [15]:
# 抽 10% 的 31091 筆 + 微調後 + TAIDE
df = pd.read_csv('exp_outputs/asy_mapping_infer_evaluation_results/google_inference_result_qlora_1250_TAIDE.csv')
df.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
bl_and_truth_bleu_score,31082.0,0.983934,0.036854,1.054769e-154,0.976877,1.000000,1.0,1.0
bl_and_truth_gleu_score,31082.0,0.990443,0.021091,5.714286e-01,0.985915,1.000000,1.0,1.0
model_and_truth_bleu_score,31082.0,0.914462,0.097448,0.000000e+00,0.878742,0.931838,1.0,1.0
model_and_truth_gleu_score,31082.0,0.946443,0.065901,0.000000e+00,0.924823,0.958159,1.0,1.0
rev_and_truth_bleu_score,31082.0,0.975779,0.046625,1.531972e-231,0.960133,1.000000,1.0,1.0
rev_and_truth_gleu_score,31082.0,0.985600,0.026009,2.857143e-01,0.976000,1.000000,1.0,1.0

In [19]:
# 抽 10% 的 31091 筆 + 未微調 + TAIDE
df = pd.read_csv('exp_outputs/asy_mapping_infer_evaluation_results/google_inference_result_org_TAIDE.csv')
df.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
bl_and_truth_bleu_score,31082.0,0.983934,0.036854,1.054769e-154,9.768770e-01,1.000000,1.000000,1.0
bl_and_truth_gleu_score,31082.0,0.990443,0.021091,5.714286e-01,9.859155e-01,1.000000,1.000000,1.0
model_and_truth_bleu_score,31082.0,0.112381,0.158692,0.000000e+00,8.579099e-79,0.050664,0.148852,1.0
model_and_truth_gleu_score,31082.0,0.209995,0.183206,0.000000e+00,9.034960e-02,0.138159,0.248641,1.0
rev_and_truth_bleu_score,31082.0,0.983215,0.038205,1.054769e-154,9.749308e-01,1.000000,1.000000,1.0
rev_and_truth_gleu_score,31082.0,0.990001,0.021779,5.714286e-01,9.847716e-01,1.000000,1.000000,1.0